# production grade
# environment variables from orchestration would override default environment setup
version: "3.7"
services:
  apiserver:
    # container_name is ignored in swarm mode
    # can't use *-api as router name.
    image: rabelais/portfolio_api:latest
    labels:
      - traefik.http.routers.portfolio-apiserver.rule=Host(`api.sungryeol.com`)
      - traefik.http.routers.portfolio-apiserver.entrypoints=web
      - traefik.enable=true
    restart: always
    environment:
      - ENV=production
      - PORT=4500
      # equivalent to postgres://db:5432
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=admin
      - DB_NAME=portfolio
      - URL=http://api.sungryeol.com
      # must include /login
      - REDIRECT_URL=http://admin.sungryeol.com/login
      # CORS setting
      - ALLOWED_ORIGINS=http://sungryeol.com,http://admin.sungryeol.com
      # secrets(will be later provided via file)
      - SECRET_PATH=/run/secrets
      - DB_PASSWORD_FILE=portfolio-db-password
      - SECRET_JWT_FILE=portfolio-secret-jwt
      - GOOGLE_ID_FILE=portfolio-google-client-id
      - GOOGLE_SECRET_FILE=portfolio-google-client-secret
      - ADMIN_GMAIL_ACCOUNT_FILE=portfolio-admin-gmail-account
      - SSL_MODE=disable
      # - SSL_MODE=verify-ca
      # - SSL_ROOT_CERT=
      # - SSL_CERT=
      # - SSL_KEY=
    ports:
      - 80:4500
    secrets:
      - portfolio-admin-gmail-account
      - portfolio-google-client-id
      - portfolio-google-client-secret
      - portfolio-secret-jwt
      - portfolio-db-password

  db:
    image: postgres:13
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD_FILE=/run/secrets/portfolio-db-password
      - POSTGRES_DB=portfolio
    volumes:
      - db-data:/var/lib/postgresql/data
    secrets:
      - portfolio-db-password

  front-www:
    restart: always
    image: rabelais/portfolio_front_www:latest
    labels:
      - traefik.http.routers.portfolio-front-www.rule=Host(`www.sungryeol.com`)
      - traefik.http.routers.portfolio-front-www.entrypoints=web
      - traefik.enable=true
    environment:
      - PORT=3000
      - NEXT_PUBLIC_API_URL=http://api.sungryeol.com
    ports:
      # listen to 3000 and out to 80
      - 80:3000

  # https://hub.docker.com/_/nginx
  front-admin:
    image: rabelais/portfolio_front_admin:latest
    labels:
      - traefik.http.routers.portfolio-front-admin.rule=Host(`admin.sungryeol.com`)
      - traefik.http.routers.portfolio-front-admin.entrypoints=web
      - traefik.enable=true
      # API_URL is provided via dockerfile
      # -> environment variable is precompiled
    ports:
      - 80:80

  reverse-proxy:
    image: traefik:v2.2
    labels:
      - traefik.http.routers.traefik.rule=Host(`traefik.sungryeol.com`)
      - traefik.http.routers.traefik.entrypoints=web
      - traefik.enable=true
    ports:
      - 80:80
      # web ui(--api.insecure=true)
      - 8080:8080
    volumes:
      - /srv/traefik.yaml:/etc/traefik/traefik.yaml
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  backend:
    driver: overlay
volumes:
  db-data:
secrets:
  portfolio-admin-gmail-account:
    external: true
  portfolio-google-client-id:
    external: true
  portfolio-google-client-secret:
    external: true
  portfolio-secret-jwt:
    external: true
  portfolio-db-password:
    external: true