# production grade
# environment variables from orchestration would override default environment setup
# Docker Swarm does not provide any port detection information to Traefik.
# Therefore you must specify the port to use
version: "3.7"
services:
  apiserver:
    # container_name is ignored in swarm mode
    # can't use *-api as router name.
    image: rabelais/portfolio_api:latest
    deploy:
      labels:
        - traefik.http.routers.portfolio_apiserver.rule=Host(`api.sungryeol.com`)
        - traefik.http.routers.portfolio_apiserver.entrypoints=web
        - traefik.http.services.portfolio_apiserver.loadbalancer.server.port=6000
        - traefik.enable=true
        - traefik.docker.network=traefik
        # - traefik.http.routers.portfolio_apiserver.tls=true
        # - traefik.http.routers.portfolio_apiserver.tls.certresolver=myresolver
        # - traefik.http.routers.portfolio_apiserver.middlewares=portfolio_https_redirect
    environment:
      - ENV=production
      - PORT=6000
      # equivalent to postgres://db:5432
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=admin
      - DB_NAME=portfolio
      - URL=https://api.sungryeol.com
      # must include /login
      - REDIRECT_URL=https://admin.sungryeol.com/login
      # CORS setting
      - ALLOWED_ORIGINS=https://sungryeol.com,http://admin.sungryeol.com
      # secrets(will be later provided via file)
      - SECRET_PATH=/run/secrets
      - DB_PASSWORD_FILE=portfolio-db-password
      - SECRET_JWT_FILE=portfolio-secret-jwt
      - GOOGLE_ID_FILE=portfolio-google-client-id
      - GOOGLE_SECRET_FILE=portfolio-google-client-secret
      - ADMIN_GMAIL_ACCOUNT_FILE=portfolio-admin-gmail-account
      - S3_ACCESS_ID_FILE=portfolio-s3-access-id
      - S3_ACCESS_SECRET_FILE=portfolio-s3-access-secret
      - S3_REGION=ap-northeast-2
      - S3_IMAGE_BUCKET=sr-portfolio-prod
      - SSL_MODE=disable
      # - SSL_MODE=verify-ca
      # - SSL_ROOT_CERT=
      # - SSL_CERT=
      # - SSL_KEY=
    ports:
      - 4500:4500
    secrets:
      - portfolio-admin-gmail-account
      - portfolio-google-client-id
      - portfolio-google-client-secret
      - portfolio-secret-jwt
      - portfolio-db-password
      - portfolio-s3-access-id
      - portfolio-s3-access-secret
    networks:
      - traefik
    volumes:
      - apiserver-file:/go/src/files
  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD_FILE=/run/secrets/portfolio-db-password
      - POSTGRES_DB=portfolio
    deploy:
      labels:
        - traefik.enable=false
    volumes:
      - db-data:/var/lib/postgresql/data
    secrets:
      - portfolio-db-password
    networks:
      - traefik

  front-www:
    image: rabelais/portfolio_front_www:latest
    deploy:
      labels:
        - traefik.http.routers.portfolio_front-www.rule=Host(`sungryeol.com`,`www.sungryeol.com`)
        - traefik.http.routers.portfolio_front-www.entrypoints=web
        - traefik.http.services.portfolio_front-www.loadbalancer.server.port=3000
        - traefik.enable=true
        - traefik.docker.network=traefik
        # - traefik.http.routers.portfolio_front-www.tls=true
        # - traefik.http.routers.portfolio_front-www.tls.certresolver=myresolver
        # - traefik.http.routers.portfolio_front-www.tls.domains[0].main=sungryeol.com
        # - traefik.http.routers.portfolio_front-www.tls.domains[0].sans=www.sungryeol.com
        # - traefik.http.routers.portfolio_front-www.middlewares=portfolio_https_redirect
    environment:
      - PORT=3000
      - NEXT_PUBLIC_API_URL=https://api.sungryeol.com
      - NEXT_PUBLIC_IMAGE_URL=https://d3cj1qm2zjlx16.cloudfront.net
      # - NEXT_PUBLIC_ASSET_URL=https://d2sqdns711i0ti.cloudfront.net/assets
    ports:
      - 3000:3000
    networks:
      - traefik

  # https://hub.docker.com/_/nginx
  front-admin:
    image: rabelais/portfolio_front_admin:latest
    deploy:
      labels:
        - traefik.http.routers.portfolio_front-admin.rule=Host(`admin.sungryeol.com`)
        - traefik.http.routers.portfolio_front-admin.entrypoints=web
        - traefik.http.services.portfolio_front-admin.loadbalancer.server.port=80
        - traefik.enable=true
        - traefik.docker.network=traefik
        # - traefik.http.routers.portfolio_front-admin.tls=true
        # - traefik.http.routers.portfolio_front-admin.tls.certresolver=myresolver
        # - traefik.http.routers.portfolio_front-admin.middlewares=portfolio_https_redirect
        # API_URL is provided via dockerfile
        # -> environment variable is precompiled
    ports:
      # listen to 80 and out to 5000
      - 5000:80
    networks:
      - traefik

  reverse-proxy:
    image: traefik:v2.2
    deploy:
      placement:
        constraints:
          - node.role == manager
          # only nodes with this label are allowed for Traefik
          # as it is the only node accessible to ACME.json volume. worker nodes doesn't have access to files
          # - node.labels.traefik-public.traefik-public-certificates == true
      labels:
        - traefik.http.routers.portfolio_reverse-proxy.rule=Host(`traefik.sungryeol.com`)
        - traefik.http.routers.portfolio_reverse-proxy.entrypoints=web
        - traefik.http.services.portfolio_reverse-proxy.loadbalancer.server.port=8080
        - traefik.enable=true
        - traefik.docker.network=traefik
        # - traefik.http.routers.portfolio_reverse-proxy.tls=true
        # - traefik.http.routers.portoflio_reverse-proxy.tls.certresolver=myresolver
        # labeling node for certification
        # - traefik.tags=traefik-public
        # - traefik.http.routers.portfolio_reverse-proxy.middlewares=portfolio_https_redirect
        # - traefik.http.middlewares.portfolio_redirect.redirectscheme.scheme=https
        # - traefik.http.middlewares.portfolio_redirect.redirectscheme.permanent=true
    ports:
      - 80:80
      - 443:443
      # web ui(--api.insecure=true)
      - 8080:8080
    volumes:
      - /srv/traefik.yaml:/etc/traefik/traefik.yaml
      - /var/run/docker.sock:/var/run/docker.sock
      # - /srv/acme.json:/acme.json
    networks:
      - traefik

networks:
  traefik:
    driver: overlay
    attachable: true
    name: traefik
volumes:
  db-data:
  apiserver-file:
secrets:
  portfolio-admin-gmail-account:
    external: true
  portfolio-google-client-id:
    external: true
  portfolio-google-client-secret:
    external: true
  portfolio-secret-jwt:
    external: true
  portfolio-db-password:
    external: true
  portfolio-s3-access-id:
    external: true
  portfolio-s3-access-secret:
    external: true
